export const anticreticSafeAbi = [
  {
    inputs: [{ internalType: 'address', name: '_asUSDToken', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'AgreementDoesNotExist', type: 'error' },
  { inputs: [], name: 'AmountNotRegistered', type: 'error' },
  { inputs: [], name: 'InvalidAddress', type: 'error' },
  { inputs: [], name: 'InvalidDates', type: 'error' },
  { inputs: [], name: 'InvalidHash', type: 'error' },
  { inputs: [], name: 'InvalidStatus', type: 'error' },
  { inputs: [], name: 'NotParticipant', type: 'error' },
  { inputs: [], name: 'OnlyOccupant', type: 'error' },
  { inputs: [], name: 'OnlyPropertyOwner', type: 'error' },
  { inputs: [], name: 'ViewerAlreadyGranted', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'approvedBy', type: 'address' },
    ],
    name: 'AgreementApproved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'propertyOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'occupant', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'propertyHash', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'startDate', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'endDate', type: 'uint256' },
    ],
    name: 'AgreementCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'registeredBy', type: 'address' },
      { indexed: true, internalType: 'address', name: 'asUSDToken', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'asUSDOperationHash', type: 'bytes32' },
    ],
    name: 'ConfidentialAmountRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'openedBy', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'reasonHash', type: 'bytes32' },
    ],
    name: 'DisputeOpened',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'bytes32', name: 'documentType', type: 'bytes32' },
      { indexed: false, internalType: 'bytes32', name: 'documentHash', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'uploadedBy', type: 'address' },
    ],
    name: 'DocumentHashUploaded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'confirmedBy', type: 'address' },
    ],
    name: 'MoneyReturnedConfirmed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'confirmedBy', type: 'address' },
    ],
    name: 'PossessionDeliveryConfirmed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'confirmedBy', type: 'address' },
    ],
    name: 'PropertyReturnedConfirmed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: false, internalType: 'uint8', name: 'newStatus', type: 'uint8' },
    ],
    name: 'StatusChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'viewer', type: 'address' },
      { indexed: true, internalType: 'address', name: 'approvedBy', type: 'address' },
    ],
    name: 'ViewerApprovalSubmitted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'viewer', type: 'address' },
    ],
    name: 'ViewerGranted',
    type: 'event',
  },
  {
    inputs: [],
    name: 'DOC_AGREEMENT_CONTRACT',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'DOC_CLOSURE_PROOF',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'DOC_POSSESSION_DELIVERY',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'DOC_PUBLIC_REGISTRY_PROOF',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'DOC_TITLE_REPORT',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'agreementCounter',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'agreementId', type: 'uint256' }],
    name: 'approveAgreement',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { internalType: 'address', name: 'viewer', type: 'address' },
    ],
    name: 'approveAmountViewer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'asUSDToken',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { internalType: 'bytes32', name: 'closureProofHash', type: 'bytes32' },
    ],
    name: 'closeAgreement',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'occupant', type: 'address' },
      { internalType: 'bytes32', name: 'propertyHash', type: 'bytes32' },
      { internalType: 'uint256', name: 'startDate', type: 'uint256' },
      { internalType: 'uint256', name: 'endDate', type: 'uint256' },
    ],
    name: 'createAgreement',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'deployer',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'agreementId', type: 'uint256' }],
    name: 'getAgreementApprovals',
    outputs: [
      { internalType: 'bool', name: 'propertyOwnerApproved', type: 'bool' },
      { internalType: 'bool', name: 'occupantApproved', type: 'bool' },
      { internalType: 'bool', name: 'propertyOwnerConfirmedPossessionDelivery', type: 'bool' },
      { internalType: 'bool', name: 'occupantConfirmedPossessionReceived', type: 'bool' },
      { internalType: 'bool', name: 'occupantConfirmedMoneyReturned', type: 'bool' },
      { internalType: 'bool', name: 'propertyOwnerConfirmedPropertyReturned', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'agreementId', type: 'uint256' }],
    name: 'getAgreementCore',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'address', name: 'propertyOwner', type: 'address' },
      { internalType: 'address', name: 'occupant', type: 'address' },
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'startDate', type: 'uint256' },
      { internalType: 'uint256', name: 'endDate', type: 'uint256' },
      { internalType: 'bool', name: 'amountRegistered', type: 'bool' },
      { internalType: 'uint8', name: 'status', type: 'uint8' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'agreementId', type: 'uint256' }],
    name: 'getAgreementHashes',
    outputs: [
      { internalType: 'bytes32', name: 'propertyHash', type: 'bytes32' },
      { internalType: 'bytes32', name: 'titleReportHash', type: 'bytes32' },
      { internalType: 'bytes32', name: 'agreementContractHash', type: 'bytes32' },
      { internalType: 'bytes32', name: 'publicRegistryProofHash', type: 'bytes32' },
      { internalType: 'bytes32', name: 'possessionDeliveryHash', type: 'bytes32' },
      { internalType: 'bytes32', name: 'closureProofHash', type: 'bytes32' },
      { internalType: 'bytes32', name: 'asUSDOperationHash', type: 'bytes32' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'agreementId', type: 'uint256' }],
    name: 'getEncryptedAmountHandle',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { internalType: 'address', name: 'viewer', type: 'address' },
    ],
    name: 'getViewerApproval',
    outputs: [
      { internalType: 'bool', name: 'propertyOwnerApproved', type: 'bool' },
      { internalType: 'bool', name: 'occupantApproved', type: 'bool' },
      { internalType: 'bool', name: 'granted', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'agreementId', type: 'uint256' }],
    name: 'occupantConfirmMoneyReturned',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'agreementId', type: 'uint256' }],
    name: 'occupantConfirmPossessionReceived',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { internalType: 'bytes32', name: 'reasonHash', type: 'bytes32' },
    ],
    name: 'openDispute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { internalType: 'bytes32', name: 'possessionDeliveryHash', type: 'bytes32' },
    ],
    name: 'propertyOwnerConfirmPossessionDelivery',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'agreementId', type: 'uint256' }],
    name: 'propertyOwnerConfirmPropertyReturned',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { internalType: 'bytes32', name: 'encryptedAmountHandle', type: 'bytes32' },
      { internalType: 'bytes', name: 'inputProof', type: 'bytes' },
      { internalType: 'bytes32', name: 'asUSDOperationHash', type: 'bytes32' },
    ],
    name: 'registerConfidentialAmount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { internalType: 'bytes32', name: 'agreementContractHash', type: 'bytes32' },
    ],
    name: 'uploadAgreementContractHash',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { internalType: 'bytes32', name: 'publicRegistryProofHash', type: 'bytes32' },
    ],
    name: 'uploadPublicRegistryProofHash',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'agreementId', type: 'uint256' },
      { internalType: 'bytes32', name: 'titleReportHash', type: 'bytes32' },
    ],
    name: 'uploadTitleReportHash',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const

